[package]
name = "devonnuri_wiki"
version = "0.1.0"
edition = "2021"
homepage = "https://wiki.onnuri.dev"
repository = "https://github.com/devonnuri/devonnuri.github.io/"

[features]
log=[]
debug=[]

[dependencies]
toml="0.7.6"